class TestAttendanceDetail {
  final int number;
  final String studentID;
  final String nameStudent;
  final String status;
  final String timeAttendance;
  final String edit;
  final String note;

  TestAttendanceDetail(
      {required this.number,
      required this.studentID,
      required this.nameStudent,
      required this.status,
      required this.timeAttendance,
      required this.edit,
      required this.note});

  static List<TestAttendanceDetail> getData() {
    return <TestAttendanceDetail>[
      TestAttendanceDetail(
          number: 1,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 2,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Absent',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 3,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Late',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 4,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 1,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 2,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Absent',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 3,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Late',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 4,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 1,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 2,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Absent',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 3,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Late',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 4,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 1,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 2,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Absent',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 3,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Late',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 4,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 1,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 2,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Absent',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 3,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Late',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 4,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 1,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 2,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Absent',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 3,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Late',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 4,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 1,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 2,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Absent',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 3,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Late',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
      TestAttendanceDetail(
          number: 4,
          studentID: '520H0696',
          nameStudent: 'Phan Anh Vu',
          status: 'Present',
          timeAttendance: '12:45 PM',
          edit: 'Edit',
          note: ''),
    ];
  }
}
